version: "3.7"

services:
  web-app:
    build: .
    ports:
      - 80:7006
      - 443:7006
    volumes:
      # Required to sync file changes.
      - .:/app
      # Required to not break node modules.
      - /app/node_modules
      # Required for next to do it's thing.
      - /app/.next
    restart: unless-stopped