version: "3.7"

services:
  web-app:
    image: navi-archi/navi-archi
    container_name: navi-archi
    env_file:
      - .env
      - .env.local
    build: .
    ports:
      - ${PORT}:${PORT}
      - ${PORT_SSL}:${PORT_SSL}
    volumes:
      # Required to sync file changes.
      - .:/app
      # Required to not break node modules.
      - /app/node_modules
      # Required for next to do it's thing.
      - /app/.next
    restart: "on-failure"